admin_blog_home:
    resource: "@AdminBlogBundle/Controller/"
    type:     annotation
    prefix:   /admin/blog/

admin_setting:
    resource: "@AdminSettingBundle/Controller/"
    type:     annotation
    prefix:   /

admin_pages:
    resource: "@AdminPagesBundle/Controller/"
    type:     annotation
    prefix:   /

_index:
    pattern:  /
    defaults: { _controller: AdminBlogBundle:Blog:showAll }

admin_admin:
    resource: "@AdminAdminBundle/Controller/"
    type:     annotation
    prefix:   /




login:
    pattern:   /login/
    defaults:  { _controller: AdminAdminBundle:Login:login}
logout:
    path:     /logout
login_check:
    pattern:   /login_check

dashboard:
    pattern: /admin/dashboard/
    defaults: {_controller: AdminDashboardBundle:Admin:index }