#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    encoders:
        Admin\AdminBundle\Entity\Admin: sha512

    role_hierarchy:
        ROLE_USER:        [ROLE_BLOGGER, ROLE_EVENT_MANAGER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_EVENT_MANAGER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_database_users:
            entity: { class: AdminAdminBundle:Admin }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /login
                invalidate_session: false
            anonymous: ~
            switch_user: ~
            remember_me:
                key: The name of our cat is Edgar!
        public:
            pattern:    /.*
            security:   false
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }