<?php

namespace Admin\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCategoryRepository extends EntityRepository
{
	public function findAll()
    {
        return $this->findBy(array(), array('name' => 'ASC'));
    }
}
