<?php

namespace Admin\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
	public function findByBlogAndCategory()
    {
        /*return $this->getEntityManager()->createQuery('SELECT b,c FROM AdminBlogBundle:Blog b
                  JOIN AdminBlogCategoryBundle:BlogCategory c
                  WHERE b.category=c.id')
        ->getResult();
        */
       $em = $this->getEntityManager();

		$query = $em->createQuery('
		    SELECT c,b
		    FROM AdminBlogBundle:Blog b
		    JOIN  AdminBlogCategoryBundle:BlogCategory c
		    WHERE b.category = c.id
		');

		//$query->setParameter('id', '1');

		return $query->getResult();
    }
}
