<?php

namespace Blog\CategoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogCategeoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCategeoryRepository extends EntityRepository
{
}
